#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N lipkin_cav
#PBS -q workq
#PBS -l select=4:ncpus=8:mpiprocs=8
#PBS -o lipkin_cav.out 
#PBS -j oe
#PBS -l walltime=360:00:00 
#----------------------------------------------------------

set -euo pipefail

# Prevents inner-thread spawning (OpenBLAS/MKL) from fighting for cores
export OMP_NUM_THREADS=1
export PYTHONWARNINGS="ignore"

# Suppress harmless OpenMPI MCA component load warnings
export MCA_param_files=/dev/null
export OMPI_MCA_pnet=^opa
export OMPI_MCA_oob=^ud

# Start timer
start=$(date +%s.%N)

# Change to submission directory
cd "$PBS_O_WORKDIR"

# Load system OpenHPC & OpenMPI modules
module load ohpc
module load openmpi3   # Make sure system openmpi module is loaded

# Activate Conda environment
CONDA_ENV=hpc
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONDA_ENV"

# Ensure PATH uses the Conda binaries first
export PATH="$CONDA_PREFIX/bin:$PATH"

PYFILE="$PBS_O_WORKDIR/Codes/lipkin_cavity_popstd.py"

PBS_NCPUS=$(wc -l < "$PBS_NODEFILE")

echo "Starting job on $PBS_NCPUS cores across allocated nodes..."
echo '---------------------------------------------'

# Run with mpiexec using OpenMPI parameters
mpiexec -n "$PBS_NCPUS" \
    --mca pnet ^opa \
    --mca oob ^ud \
    python -u "$PYFILE" --g 0.001 --output cavity_population_sweep_checkpoint_lowlowg.npz

# End timer
end=$(date +%s.%N)

RUNTIME=$(echo "$end - $start" | bc -l)

echo '---------------------------------------------'
echo "Completed in: $RUNTIME sec"
echo '---------------------------------------------'

# Define login node
LOGIN_NODE="kuhpchn"

# Define the ntfy.sh URL
NTFY_URL="https://ntfy.sh/kuhpchn"

# Define the message payload
MESSAGE="Job '$PBS_JOBID' finished on kuhpchn in '$RUNTIME' secs. Check output @ '$PBS_O_WORKDIR'"

# SSH into the login node and execute the curl command remotely
sshpass -f $HOME/.password ssh "$LOGIN_NODE" "curl -X POST -d \"$MESSAGE\" \"$NTFY_URL\""
